archive = "bionic"
version = "18.04"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "michael@system76.com"

[[repos]]
repo = "http://ppa.launchpad.net/js-reynaud/kicad-5/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64" }
name = { not = "dbg"}

[[repos]]
repo = "http://ppa.launchpad.net/freecad-maintainers/freecad-stable/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64" }

# Peek GTK application
[[repos]]
repo = "http://ppa.launchpad.net/peek-developers/stable/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64"}

# Updated stable scribus (1.4.x), and scribus-ng (1.5.x)
[[repos]]
repo = "http://ppa.launchpad.net/scribus/ppa/ubuntu/pool/main/"
version = { is = "ubuntu18.04" }
arch = { is = "all|amd64" }
name = { not = "dbg"}

[[direct]]
name = "atom"
version = "1.53.0"

    [[direct.urls]]
    url = "https://github.com/atom/atom/releases/download/v1.53.0/atom-amd64.deb"
    checksum = "dd9198204d99aace37c7c01087ab16bc7179d1a04b3d9d24371d3e68c1b27b2d"

[[direct]]
name = "mattermost-desktop"
version = "4.3.2"

    [[direct.urls]]
    url = "https://releases.mattermost.com/desktop/${version}/${name}-${version}-linux-amd64.deb"
    checksum = "d43ef2f1ea3b2b4b7b1b97a6de598e25d7a8c8f5e82404f4b73cfef89b3dd120"

[[direct]]
name = "wire-desktop"
version = "3.11.2912"

    [[direct.urls]]
    url = "https://github.com/wireapp/wire-desktop/releases/download/linux%2F${version}/Wire-${version}_amd64.deb"
    checksum = "540fbe94161ea52e7406b8df94842eae4abe22707f5baab7680d94d346505cb4"

[[direct]]
name = "github-desktop"
version = "2.1.0-linux1"

    [[direct.urls]]
    arch = "amd64"
    url = "https://github.com/shiftkey/desktop/releases/download/release-2.1.0-linux1/GitHubDesktop-linux-2.1.0-linux1.deb"
    checksum = "8dd4cf7ea4df04a245c1b9b49102dc6f060084de52f2fdc44bbf0280ffe40077"

# [[source]]
# name = "piserver"
# build_on = "changelog"

#     [source.location]
#     git = "https://github.com/raspberrypi/piserver"
