archive = "groovy"
version = "20.10"
origin = "system76-curated-free"
label = "System76 Curated Free Software"
email = "info@system76.com"

[[direct]]
name = "atom"
version = "1.53.0"

    [[direct.urls]]
    url = "https://github.com/atom/atom/releases/download/v1.53.0/atom-amd64.deb"
    checksum = "dd9198204d99aace37c7c01087ab16bc7179d1a04b3d9d24371d3e68c1b27b2d"

[[direct]]
name = "github-desktop"
version = "2.4.1-linux1"

    [[direct.urls]]
    arch = "amd64"
    url = "https://github.com/shiftkey/desktop/releases/download/release-${version}/GitHubDesktop-linux-${version}.deb"
    checksum = "5339a240b549656cfcf948d98002f03842914d7eaa6ed0548e352e30ffa4b683"

# [[source]]
# name = "piserver"
# build_on = "changelog"

#     [source.location]
#     git = "https://github.com/raspberrypi/piserver"
